name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up notebook state cache
      uses: actions/cache@v2
      with:
        path: pluto_state_cache
        key: ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ hashFiles('**/*.jl') }}
        restore-keys: |
             ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.6
    - name: Run Pluto notebooks
      run: julia --project=pluto-deployment-environment -e '
          import Pkg;
          Pkg.instantiate();
          using PlutoSliderServer;
          github_action("."; Export_cache_dir="pluto_state_cache");'
    - name: Franklin
      run: julia -e '
          using Pkg;
          Pkg.add([
          Pkg.PackageSpec(name="NodeJS", version="1.1.1"),
          Pkg.PackageSpec(name="JSON", version="0.21.1"),
          Pkg.PackageSpec(name="Franklin", version="0.10.28"),
          ]);
          using NodeJS;

          "== Run Franklin ==";
          cd("website");

          run(`$(npm_cmd()) install highlight.js`);
          using Franklin;
          optimize(;minify=false);
          "== Place rendered notebooks in the website folder ==";
          cp("../notebooks", "__site/notebooks");'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: website/__site